# fedora-44-stock — the RPM family's leading edge, untouched.
#
# Fedora diverges from the Debian bundles exactly where AUTH and SERVICES are
# most opinionated. Its PAM stacks are generated by authselect rather than
# hand-assembled — /etc/pam.d/system-auth and password-auth are symlinks into
# /etc/authselect/ — and a parser that assumed the Debian shape of a stack would
# reach the wrong verdict here while looking entirely confident about it.
# /etc/login.defs, the shipped sysctl drop-ins and the default umask all differ
# too.
#
# The UNKNOWN this bundle records is AUTH-0002, and it is worth reading: Fedora
# enforces pam_pwquality and then sets none of its parameters, so the effective
# minimum password length comes from libpwquality's compiled-in default. That is
# a property of a binary rather than of any file on this host, so the check
# declines to report it.
#
# The tag is `latest` in the recipe and the version in the bundle's name,
# because the name has to say what was actually recorded and `latest` will mean
# something else next quarter. Check the PRETTY_NAME in the recorded bundle
# before renaming this file after a re-record.
FROM fedora:latest
