// Command gendocs writes docs/MODULE-CATALOG.md and docs/CHECK-REFERENCE.md
// from the catalog this binary carries.
//
// docs/DOCUMENT-MAP.md marks both as *generated* and says they are never
// hand-maintained, and the reason is the one that makes generated reference
// documentation worth having at all: a hand-written list of 79 checks is a list
// that is wrong within a month, and wrong reference documentation for a
// security tool is worse than none, because somebody will act on it.
//
// The catalog comes from cli.Catalog(), which is the same assembly the binary
// evaluates with. There is no second list of checks: a document generated from
// a copy would describe a catalog nobody runs.
//
// Two modes, mirroring tools/fixturegate:
//
//	go run ./tools/gendocs           write the files
//	go run ./tools/gendocs -check    exit 1 if they are out of date
//
// The second is wired into `make invariants`, so a check added without
// regenerating is a failed build rather than a discovery six months later.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/antaryx/plumbline/internal/catalog"
	"github.com/antaryx/plumbline/internal/cli"
	"github.com/antaryx/plumbline/internal/version"
)

const docsDir = "docs"

// generatedBanner heads both files. It is not decoration: without it the first
// person to find a typo fixes it in the output, the fix survives exactly until
// the next regeneration, and they conclude the generator ate their work.
const generatedBanner = `<!-- Generated by tools/gendocs. Do not edit.
     Run ` + "`make docs`" + ` after changing the catalog. -->`

func main() {
	check := flag.Bool("check", false, "verify the committed files are current instead of writing them")
	flag.Parse()

	c := cli.Catalog()
	files := map[string]string{
		"MODULE-CATALOG.md":  moduleCatalog(c),
		"CHECK-REFERENCE.md": checkReference(c),
	}

	if *check {
		if err := verify(files); err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("ok: generated docs current (%d checks, catalog %d)\n", c.Len(), version.Catalog())
		return
	}

	for name, body := range files {
		path := filepath.Join(docsDir, name)
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil { //nolint:gosec // a documentation file
			fmt.Fprintf(os.Stderr, "gendocs: writing %s: %v\n", path, err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s\n", path)
	}
}

func verify(files map[string]string) error {
	for _, name := range sortedKeys(files) {
		path := filepath.Join(docsDir, name)
		got, err := os.ReadFile(path) //nolint:gosec // a documentation file
		if err != nil {
			return fmt.Errorf("%s is missing; run `make docs`", path)
		}
		if string(got) != files[name] {
			return fmt.Errorf("%s is out of date; run `make docs` and commit the result", path)
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// MODULE-CATALOG.md
// ---------------------------------------------------------------------------

func moduleCatalog(c *catalog.Catalog) string {
	var b strings.Builder
	header(&b, c, "Module catalog",
		"Every module this build carries, and how many checks each contributes. "+
			"The per-check detail is in [CHECK-REFERENCE.md](CHECK-REFERENCE.md).")

	mods := modules(c)

	b.WriteString("| Module | Checks | Critical | High | Medium | Low | Info |\n")
	b.WriteString("|---|---:|---:|---:|---:|---:|---:|\n")
	var total int
	totals := map[string]int{}
	for _, m := range mods {
		sev := severities(m.checks)
		fmt.Fprintf(&b, "| `%s` | %d | %d | %d | %d | %d | %d |\n",
			m.name, len(m.checks),
			sev["CRITICAL"], sev["HIGH"], sev["MEDIUM"], sev["LOW"], sev["INFO"])
		total += len(m.checks)
		for k, v := range sev {
			totals[k] += v
		}
	}
	fmt.Fprintf(&b, "| **total** | **%d** | %d | %d | %d | %d | %d |\n\n",
		total, totals["CRITICAL"], totals["HIGH"], totals["MEDIUM"], totals["LOW"], totals["INFO"])

	b.WriteString("Severity is the check's **base** severity, before any context " +
		"adjustment a finding may carry.\n\n---\n\n")

	for _, m := range mods {
		fmt.Fprintf(&b, "## %s\n\n", m.name)
		b.WriteString("| Check | Severity | Reads |\n|---|---|---|\n")
		for _, ck := range m.checks {
			fmt.Fprintf(&b, "| [`%s`](CHECK-REFERENCE.md#%s) %s | %s | %s |\n",
				ck.ID, anchor(ck.ID, ck.Title), escape(ck.Title),
				ck.BaseSeverity, factList(ck))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// CHECK-REFERENCE.md
// ---------------------------------------------------------------------------

func checkReference(c *catalog.Catalog) string {
	var b strings.Builder
	header(&b, c, "Check reference",
		"One entry per check: what it tests, which facts it reads, how to fix what "+
			"it finds, and what it maps to. This is `plumbline explain CHECK-ID` "+
			"for the whole catalog at once — the command is the same material and "+
			"needs no network, no bundle and no privileges.")

	for _, m := range modules(c) {
		fmt.Fprintf(&b, "## %s\n\n", m.name)
		for _, ck := range m.checks {
			entry(&b, ck)
		}
	}
	return b.String()
}

func entry(b *strings.Builder, ck catalog.Check) {
	fmt.Fprintf(b, "### %s — %s\n\n", ck.ID, escape(ck.Title))

	if ck.Deprecated != nil {
		fmt.Fprintf(b, "> **Deprecated since catalog %d.** %s\n",
			ck.Deprecated.SinceCatalog, escape(ck.Deprecated.Reason))
		if len(ck.Deprecated.ReplacedBy) > 0 {
			fmt.Fprintf(b, "> Replaced by %s.\n", code(ck.Deprecated.ReplacedBy))
		}
		b.WriteString(">\n> A retired ID is never reused and never renumbered: it is in\n" +
			"> suppression files and in bundles on disk.\n\n")
	}

	b.WriteString("| | |\n|---|---|\n")
	fmt.Fprintf(b, "| Module | `%s` |\n", ck.Module)
	fmt.Fprintf(b, "| Base severity | %s |\n", ck.BaseSeverity)
	fmt.Fprintf(b, "| Since | catalog %d |\n", ck.SinceCatalog)
	fmt.Fprintf(b, "| Reads | %s |\n", factList(ck))
	if len(ck.Tags) > 0 {
		fmt.Fprintf(b, "| Tags | %s |\n", code(ck.Tags))
	}
	b.WriteString("\n")

	if ck.Description != "" {
		b.WriteString(strings.TrimSpace(ck.Description) + "\n\n")
	}

	// The same sentence `plumbline explain` prints, and it is the load-bearing
	// one: a check that cannot see what it needs says UNKNOWN rather than
	// guessing, and a reader of this document has to know that before they read
	// a PASS as reassurance.
	b.WriteString("If a fact it reads was not collected — a file the scan could not read, " +
		"a collector that failed — this check reports `UNKNOWN` with a reason rather " +
		"than guessing.\n\n")

	if r := ck.Remediation; r != nil {
		fmt.Fprintf(b, "**Remediation** — effort %s\n\n", r.Effort)
		if r.Summary != "" {
			b.WriteString(escape(r.Summary) + "\n\n")
		}
		for i, step := range r.Steps {
			fmt.Fprintf(b, "%d. %s\n", i+1, escape(step))
		}
		if len(r.Steps) > 0 {
			b.WriteString("\n")
		}
		if len(r.Commands) > 0 {
			b.WriteString("```sh\n" + strings.Join(r.Commands, "\n") + "\n```\n\n")
		}
		if r.Caution != "" {
			b.WriteString("> **Caution.** " + escape(r.Caution) + "\n\n")
		}
	}

	if len(ck.Mappings) > 0 {
		var refs []string
		for _, m := range ck.Mappings {
			refs = append(refs, fmt.Sprintf("`%s %s`", m.Framework, m.Control))
		}
		fmt.Fprintf(b, "**Controls** — %s\n\n", strings.Join(refs, ", "))
	}
	if len(ck.References) > 0 {
		b.WriteString("**References**\n\n")
		for _, r := range ck.References {
			if r.URL != "" {
				fmt.Fprintf(b, "- [%s](%s)\n", escape(r.Title), r.URL)
			} else {
				fmt.Fprintf(b, "- %s\n", escape(r.Title))
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n\n")
}

// ---------------------------------------------------------------------------
// shared
// ---------------------------------------------------------------------------

func header(b *strings.Builder, c *catalog.Catalog, title, intro string) {
	b.WriteString(generatedBanner + "\n\n")
	fmt.Fprintf(b, "# %s\n\n", title)
	fmt.Fprintf(b, "**Catalog version %d · %d checks · %d modules**\n\n",
		version.Catalog(), c.Len(), len(modules(c)))
	b.WriteString(intro + "\n\n")

	// Stated in both documents rather than in one, because either may be the
	// page somebody lands on from a search engine.
	b.WriteString("Plumbline reports evidence, not compliance conclusions. " +
		"A control mapping names an identifier that a check is *relevant to*; " +
		"it is not a claim of compliance with it, and no control text is " +
		"reproduced here (see [COMPLIANCE-DATA-POLICY.md](COMPLIANCE-DATA-POLICY.md)).\n\n---\n\n")
}

type module struct {
	name   string
	checks []catalog.Check
}

// modules groups the catalog by module, both sorted, so the generated document
// is a pure function of the catalog and two runs produce identical bytes.
func modules(c *catalog.Catalog) []module {
	byName := map[string][]catalog.Check{}
	for _, id := range c.IDs() {
		ck, ok := c.Get(id)
		if !ok {
			continue
		}
		byName[ck.Module] = append(byName[ck.Module], ck)
	}

	names := sortedKeys(byName)
	out := make([]module, 0, len(names))
	for _, n := range names {
		checks := byName[n]
		sort.Slice(checks, func(i, j int) bool { return checks[i].ID < checks[j].ID })
		out = append(out, module{name: n, checks: checks})
	}
	return out
}

func severities(checks []catalog.Check) map[string]int {
	out := map[string]int{}
	for _, ck := range checks {
		out[strings.ToUpper(string(ck.BaseSeverity))]++
	}
	return out
}

func factList(ck catalog.Check) string {
	if len(ck.Requires) == 0 {
		return "—"
	}
	ids := make([]string, 0, len(ck.Requires))
	for _, id := range ck.Requires {
		ids = append(ids, string(id))
	}
	sort.Strings(ids)
	return code(ids)
}

func code(in []string) string {
	out := make([]string, 0, len(in))
	for _, s := range in {
		out = append(out, "`"+s+"`")
	}
	return strings.Join(out, ", ")
}

// anchor reproduces GitHub's heading-slug rule for "### ID — Title", so the
// links in MODULE-CATALOG.md land on the right entry.
func anchor(id, title string) string {
	slug := strings.ToLower(id + " — " + title)
	var b strings.Builder
	for _, r := range slug {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
			b.WriteRune(r)
		case r == ' ':
			b.WriteRune('-')
		}
	}
	return b.String()
}

// escape neutralises the Markdown a check's own prose could otherwise inject
// into a table cell. Titles and remediation steps are written by check authors
// and contain pipes, underscores and asterisks — a path like
// /etc/pam.d/*.conf ends a table row early and italicises the rest of the file.
func escape(s string) string {
	r := strings.NewReplacer(
		`|`, `\|`,
		`*`, `\*`,
		`_`, `\_`,
		"\n", " ",
	)
	return strings.TrimSpace(r.Replace(s))
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
