// Package kernel holds the KERNEL module's checks.
//
// Every check here reads one or more parameters from the kernel.sysctl fact
// and judges the running value. The shape is deliberately uniform, and the
// uniformity is enforced by the helpers in this file rather than by each check
// remembering to do the same thing: the mapping from "we could not read this
// parameter" to a result and a reason code is the part of a KERNEL check that
// is easy to get wrong and impossible to notice when it is wrong, because a
// check that returns PASS for a parameter it never read looks exactly like a
// check that passed.
//
// See docs/CHECK-AUTHORING.md, and internal/catalog/checks/sshd/sshd0002.go
// for the project's reference check.
package kernel

import (
	"fmt"
	"sort"
	"strings"

	"github.com/antaryx/plumbline/internal/catalog"
	"github.com/antaryx/plumbline/internal/fact"
	"github.com/antaryx/plumbline/internal/finding"
)

// sysctlFact reads the module's fact. The runner guarantees a check's required
// facts are present and typed before Eval is entered, so this cannot fail in a
// way a check must defend against.
func sysctlFact(fs *fact.Set) fact.Sysctl {
	sc, _, _ := fact.Get[fact.Sysctl](fs, fact.SysctlID)
	return sc
}

// unreadable converts a parameter that has no usable running value into the
// outcome that describes it.
//
// The second return is false when the parameter *was* observed, in which case
// the caller proceeds to judge the value. Every KERNEL check begins with this,
// which is how the four ways a read can fail stay mapped to four different
// verdicts instead of collapsing into a convenient PASS.
func unreadable(r fact.SysctlRunning, subject string) (catalog.Outcome, bool) {
	switch r.State {
	case fact.SysctlObserved:
		return catalog.Outcome{}, false

	case fact.SysctlAbsent:
		// The kernel does not implement this parameter, so there is nothing
		// here to harden and nothing to report against. This is the only
		// honest NOT_APPLICABLE in the module: it means the subject does not
		// exist, not that we failed to find it.
		return catalog.Outcome{
			Result:  finding.NotApplicable,
			Subject: subject,
			Detail: fmt.Sprintf(
				"This kernel does not expose %s (%s); the feature is not built in, its module is not loaded, or the LSM providing it is disabled.",
				r.Key, r.Path),
		}, true

	case fact.SysctlDenied:
		// It exists and we were refused. It may be set wrong; we cannot see.
		return catalog.Outcome{
			Result:        finding.Unknown,
			UnknownReason: finding.ReasonPermission,
			Subject:       subject,
			Detail: fmt.Sprintf(
				"%s could not be read (%s): %s. The parameter exists, so its value may or may not be correct; run as root to determine it.",
				r.Key, r.Path, r.Msg),
			Evidence: []finding.Evidence{finding.NewEvidence(r.Path, 0, r.Msg, "")},
		}, true

	default:
		return catalog.Outcome{
			Result:        finding.Unknown,
			UnknownReason: finding.ReasonAmbiguousState,
			Subject:       subject,
			Detail:        fmt.Sprintf("%s could not be read (%s): %s.", r.Key, r.Path, r.Msg),
			Evidence:      []finding.Evidence{finding.NewEvidence(r.Path, 0, r.Msg, "")},
		}, true
	}
}

// unparseable is the outcome for an observed value that is not the integer the
// parameter is documented to hold.
//
// This path is reachable in practice: a parameter can change type between
// kernel versions, and a container runtime can mount something else over
// /proc/sys. Returning a fabricated zero here would be a fabricated FAIL, and
// defaulting to the safe value would be a fabricated PASS. Neither is
// available to us.
func unparseable(r fact.SysctlRunning, subject string) catalog.Outcome {
	return catalog.Outcome{
		Result:        finding.Unknown,
		UnknownReason: finding.ReasonParse,
		Subject:       subject,
		Detail: fmt.Sprintf(
			"%s holds %q, which is not the single integer this parameter is documented to contain; its meaning cannot be determined.",
			r.Key, r.Value),
		Evidence: []finding.Evidence{evidenceFor(r)},
	}
}

// evidenceFor cites a running parameter.
//
// There is no digest: /proc/sys is generated by the kernel on read and is not
// stored in the bundle's evidence store, so there is nothing an auditor could
// re-read and hash. Passing an empty digest is the honest representation of
// that, and is why ADR-0009 makes the field optional.
func evidenceFor(r fact.SysctlRunning) finding.Evidence {
	return finding.NewEvidence(r.Path, 0, fmt.Sprintf("%s = %s", r.Key, r.Value), "")
}

// evidenceForSetting cites a configuration line, with the digest of the file it
// came from so an auditor can verify it against the bundle.
func evidenceForSetting(sc fact.Sysctl, set fact.SysctlSetting) finding.Evidence {
	return finding.NewEvidence(
		set.File, set.Line,
		fmt.Sprintf("%s = %s", set.Key, set.Value),
		sc.Digests[set.File])
}

// intCheck builds the Eval for the common shape: read one integer parameter,
// pass when it satisfies a predicate, fail otherwise.
//
// pass reports whether the observed integer is acceptable. detail renders the
// human explanation for both outcomes, which keeps the PASS and FAIL wording
// of one check in one place — a correct verdict with a misleading explanation
// is its own bug.
func intCheck(
	key string,
	pass func(int) bool,
	failSeverity func(int) finding.Severity,
	detail func(n int, ok bool) string,
) func(*fact.Set) catalog.Outcome {
	return func(fs *fact.Set) catalog.Outcome {
		sc := sysctlFact(fs)

		r, probed := sc.Run(key)
		if !probed {
			// The collector never asked for this key. That is a wiring bug in
			// this repository, not an observation about the host, and it must
			// not look like one.
			return catalog.Outcome{
				Result:        finding.Unknown,
				UnknownReason: finding.ReasonInternal,
				Subject:       key,
				Detail:        fmt.Sprintf("%s was not collected; the KERNEL collector does not probe it.", key),
			}
		}
		if out, done := unreadable(r, key); done {
			return out
		}

		n, ok := r.Int()
		if !ok {
			return unparseable(r, key)
		}

		ev := []finding.Evidence{evidenceFor(r)}
		if pass(n) {
			return catalog.Outcome{
				Result:   finding.Pass,
				Subject:  key,
				Detail:   detail(n, true),
				Evidence: ev,
			}
		}
		out := catalog.Outcome{
			Result:   finding.Fail,
			Subject:  key,
			Detail:   detail(n, false),
			Evidence: ev,
		}
		if failSeverity != nil {
			out.Severity = failSeverity(n)
		}
		// Where the configuration disagrees with the running kernel, say so on
		// the failing finding too. An operator whose file already holds the
		// right value needs to know a reboot is the fix, not another edit.
		note, ev := driftNote(sc, key, r.Value)
		out.Detail += note
		out.Evidence = append(out.Evidence, ev...)
		return out
	}
}

// driftNote returns the sentence and evidence to append to a failing finding
// when the configuration sets this parameter to something other than what is
// running.
//
// It is the reason KERNEL-0007 is not the module's only use of the configured
// values. A finding that says only "ASLR is off" sends an operator to edit a
// file that already says 2; a finding that says "and your configuration
// already sets 2" sends them to reboot instead. Same verdict, different
// afternoon.
//
// Nothing is returned when the parameter is set in more than one file with
// different values: which one wins is undetermined (see
// fact.Sysctl.ConfiguredConflict), and KERNEL-0007 reports that ambiguity on
// its own rather than every check repeating a guess about it.
func driftNote(sc fact.Sysctl, key, running string) (string, []finding.Evidence) {
	set, found := sc.EffectiveConfigured(key)
	if !found || sc.ConfiguredConflict(key) {
		return "", nil
	}
	if strings.TrimSpace(set.Value) == strings.TrimSpace(running) {
		return "", nil
	}
	return fmt.Sprintf(
			" %s is configured as %q at %s:%d, so the running kernel does not match its own configuration; see KERNEL-0007.",
			key, set.Value, set.File, set.Line),
		[]finding.Evidence{evidenceForSetting(sc, set)}
}

// runningFor resolves one parameter to the outcome that describes it when it
// has no usable value, or to the value itself when it does. It is the front
// half of every check that is not built from intCheck.
func runningFor(sc fact.Sysctl, key string) (fact.SysctlRunning, catalog.Outcome, bool) {
	r, probed := sc.Run(key)
	if !probed {
		// The collector never asked for this key. That is a wiring bug in this
		// repository, not an observation about the host.
		return r, catalog.Outcome{
			Result:        finding.Unknown,
			UnknownReason: finding.ReasonInternal,
			Subject:       key,
			Detail:        fmt.Sprintf("%s was not collected; the KERNEL collector does not probe it.", key),
		}, false
	}
	if out, done := unreadable(r, key); done {
		return r, out, false
	}
	return r, catalog.Outcome{}, true
}

// pronounFor keeps the "a setting for ..." clause grammatical whether the
// check holds one parameter or several.
func pronounFor(keys []string) string {
	if len(keys) == 1 {
		return "it"
	}
	return "them"
}

// joinKeys renders a sorted key list for a detail string.
func joinKeys(in []string) string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return strings.Join(out, ", ")
}

// ---------------------------------------------------------------------------
// persistence: the checks that read the files rather than /proc/sys
// ---------------------------------------------------------------------------

// persistenceGate answers everything a persistence check has to settle before
// it may look at a value, and returns nil when there is a value to look at.
//
// The four conditions below are the same for every check of this shape and
// each of them was a decision worth making once. Three checks now share them,
// which is the point: the ordering is a correctness property — a kernel that
// does not implement a parameter must be excused *before* an absent
// configuration is called a failure, and an unreadable file must stop the
// check *before* an absence is concluded from what was read — and three copies
// of it would be three chances to get the order wrong.
//
// The wording of the verdict is left to the caller. Everything here is about
// whether a verdict may be reached at all.
func persistenceGate(sc fact.Sysctl, keys []string, caveat string) *catalog.Outcome {
	// 1. A kernel that implements none of them has nothing for a file to
	//    persist, and a file setting them would do nothing. All of them have to
	//    be absent: a kernel with one and not the other is one this check still
	//    has something to say about.
	absent := 0
	for _, key := range keys {
		if r, probed := sc.Run(key); probed && r.State == fact.SysctlAbsent {
			absent++
		}
	}
	if absent == len(keys) {
		lead := fmt.Sprintf("This kernel implements none of %s", joinKeys(keys))
		if len(keys) == 1 {
			lead = fmt.Sprintf("This kernel does not implement %s", keys[0])
		}
		return &catalog.Outcome{
			Result:  finding.NotApplicable,
			Subject: "sysctl configuration",
			Detail:  lead + ", so there is nothing for a configuration file to persist." + caveat,
		}
	}

	// 2. No configuration at all, and nothing that stopped us reading it.
	//    There is no file to have an opinion about: an image built without
	//    them, or a host whose kernel settings arrive some other way.
	//    Reporting FAIL would be a finding about a file that was never meant
	//    to exist.
	if len(sc.Files) == 0 && len(sc.UnreadableFiles) == 0 {
		return &catalog.Outcome{
			Result: finding.NotApplicable,
			Detail: "No sysctl configuration file exists on this host: neither /etc/sysctl.conf nor any .conf file in the sysctl.d directories. There is no persistent kernel configuration to report on, and what the running kernel currently does is the business of the check that reads /proc/sys." + caveat,
		}
	}

	// 3. A file we could not read may hold the setting, so an absence cannot
	//    be concluded. This comes before the value test because every verdict
	//    below rests on *not* finding something — ADR-0014 in the direction it
	//    points here.
	if out, stop := configUnreadable(sc, keys, caveat); stop {
		return &out
	}

	// 4. Two files disagreeing has no determinable outcome: procps and
	//    systemd-sysctl walk the drop-in directories in different orders, so
	//    which value is in force after a reboot depends on which tool applied
	//    them. Guessing would be a confident claim about exactly the thing
	//    these checks report on.
	for _, key := range keys {
		if !sc.ConfiguredConflict(key) {
			continue
		}
		var (
			where []string
			ev    []finding.Evidence
		)
		for _, s := range sc.Configured[key] {
			where = append(where, fmt.Sprintf("%s:%d sets %s", s.File, s.Line, s.Value))
			ev = append(ev, evidenceForSetting(sc, s))
		}
		return &catalog.Outcome{
			Result:        finding.Unknown,
			UnknownReason: finding.ReasonAmbiguousState,
			Subject:       key,
			Detail: fmt.Sprintf("%s is set to different values in more than one configuration file (%s). Which one is in force after a reboot depends on whether systemd-sysctl or procps applied them and in what order, so what this host does on its next boot cannot be determined from the files alone.%s",
				key, strings.Join(where, "; "), caveat),
			Evidence: ev,
		}
	}
	return nil
}

// configUnreadable stops the check when a configuration file exists and could
// not be read.
//
// The keys are named in the verdict rather than described. This function was
// written for KERNEL-0017 and said "the BPF parameters" in a string, which
// every later check of this shape then reported about its own parameters —
// a ptrace finding that told the operator to go looking for BPF. A detail
// string that names the wrong subject is worse than a vague one, because it
// sends someone to the wrong file.
//
// The verdict below rests on *not* finding a setting, and a file nobody opened
// may contain it. That is ADR-0014 in the direction it points here: an
// incomplete examination invalidates a negative result.
func configUnreadable(sc fact.Sysctl, keys []string, caveat string) (catalog.Outcome, bool) {
	names := sc.UnreadableFileNames()
	if len(names) == 0 {
		return catalog.Outcome{}, false
	}

	reason := finding.ReasonAmbiguousState
	if kind, ok := sc.WorstUnreadableKind(); ok {
		switch kind {
		case fact.ErrPermission:
			reason = finding.ReasonPermission
		case fact.ErrTruncated:
			reason = finding.ReasonTruncated
		case fact.ErrParse:
			reason = finding.ReasonParse
		}
	}
	var ev []finding.Evidence
	for _, f := range sc.UnreadableFiles {
		ev = append(ev, finding.NewEvidence(f.File, 0, string(f.Kind)+": "+f.Msg, ""))
	}
	return catalog.Outcome{
		Result:        finding.Unknown,
		UnknownReason: reason,
		Subject:       "sysctl configuration",
		Detail: fmt.Sprintf("This verdict would rest on not finding %s in any configuration file, and %s could not be read — so a setting for %s may be in a file this scan never opened.%s",
			joinKeys(keys), joinKeys(names), pronounFor(keys), caveat),
		Evidence: ev,
	}, true
}

// searchedEvidence guarantees a verdict about an absence cites something.
//
// When a parameter is set nowhere there is no line to quote, and a finding with
// no evidence is one an auditor cannot follow up. What they need instead is the
// list of files that *were* read — "I looked in these and it is in none of
// them" — which is also the set an operator has to check before adding a new
// drop-in.
func searchedEvidence(sc fact.Sysctl, ev []finding.Evidence) []finding.Evidence {
	if len(ev) > 0 {
		return ev
	}
	for _, f := range sc.Files {
		note := "read, and does not set the parameter"
		if target, ok := sc.ResolvedFrom(f); ok {
			note += "; a symbolic link to " + target
		}
		ev = append(ev, finding.NewEvidence(f, 0, note, sc.Digests[f]))
	}
	return ev
}

// configuredEvidence cites one parameter's setting, or the files searched when
// it has none.
func configuredEvidence(sc fact.Sysctl, key string) []finding.Evidence {
	if set, found := sc.EffectiveConfigured(key); found {
		return []finding.Evidence{evidenceForSetting(sc, set)}
	}
	return searchedEvidence(sc, nil)
}

// configuredAt renders where a parameter got its value, which is not always
// the place its name appears.
//
// A distribution commonly sets a whole family at once —
// net.ipv4.conf.*.rp_filter = 1 — and never writes the individual key down. A
// finding that said "net.ipv4.conf.all.rp_filter is 1 at 50-redhat.conf:5"
// would send an operator to a line that does not contain that string. Naming
// the pattern instead is the difference between evidence they can follow and
// evidence they will conclude is wrong.
func configuredAt(sc fact.Sysctl, key string, set fact.SysctlSetting) string {
	if glob, ok := sc.GlobbedBy(key); ok {
		return fmt.Sprintf("by the pattern %s at %s:%d", glob.Key, glob.File, glob.Line)
	}
	return fmt.Sprintf("at %s:%d", set.File, set.Line)
}

// notConfigured renders why a parameter has no value, distinguishing a file
// that withheld it from files that simply never mention it.
//
// The two are different states of the world and only one of them is a decision
// somebody made. A key excluded by "-name" is one the distribution set for
// every interface and then deliberately left alone; telling its operator that
// "nothing sets this" would be false, and would send them to add a line whose
// absence is the point.
func notConfigured(sc fact.Sysctl, key string) string {
	if ex, ok := sc.ExcludedFrom(key); ok {
		return fmt.Sprintf("%s is withheld from glob matching by %s:%d and set by nothing else", key, ex.File, ex.Line)
	}
	return fmt.Sprintf("%s is not set in any sysctl configuration file", key)
}

// persistCaveatFor builds the sentence every persistence verdict ends with,
// naming the check that reads the running value of the same parameter.
//
// It is not decoration. These checks and their /proc/sys counterparts disagree
// on the same host all the time — that is the whole reason they both exist —
// and a reader who does not know which one they are holding will act on the
// wrong finding.
func persistCaveatFor(runtimeCheck string) string {
	return fmt.Sprintf(" This reads the sysctl configuration files, which describe what the kernel will do after the next reboot; what it is doing now is %s's subject, and a disagreement between the two is KERNEL-0007's.",
		runtimeCheck)
}
