// Package kernel holds the KERNEL module's checks.
//
// Every check here reads one or more parameters from the kernel.sysctl fact
// and judges the running value. The shape is deliberately uniform, and the
// uniformity is enforced by the helpers in this file rather than by each check
// remembering to do the same thing: the mapping from "we could not read this
// parameter" to a result and a reason code is the part of a KERNEL check that
// is easy to get wrong and impossible to notice when it is wrong, because a
// check that returns PASS for a parameter it never read looks exactly like a
// check that passed.
//
// See docs/CHECK-AUTHORING.md, and internal/catalog/checks/sshd/sshd0002.go
// for the project's reference check.
package kernel

import (
	"fmt"
	"sort"
	"strings"

	"github.com/antaryx/plumbline/internal/catalog"
	"github.com/antaryx/plumbline/internal/fact"
	"github.com/antaryx/plumbline/internal/finding"
)

// sysctlFact reads the module's fact. The runner guarantees a check's required
// facts are present and typed before Eval is entered, so this cannot fail in a
// way a check must defend against.
func sysctlFact(fs *fact.Set) fact.Sysctl {
	sc, _, _ := fact.Get[fact.Sysctl](fs, fact.SysctlID)
	return sc
}

// unreadable converts a parameter that has no usable running value into the
// outcome that describes it.
//
// The second return is false when the parameter *was* observed, in which case
// the caller proceeds to judge the value. Every KERNEL check begins with this,
// which is how the four ways a read can fail stay mapped to four different
// verdicts instead of collapsing into a convenient PASS.
func unreadable(r fact.SysctlRunning, subject string) (catalog.Outcome, bool) {
	switch r.State {
	case fact.SysctlObserved:
		return catalog.Outcome{}, false

	case fact.SysctlAbsent:
		// The kernel does not implement this parameter, so there is nothing
		// here to harden and nothing to report against. This is the only
		// honest NOT_APPLICABLE in the module: it means the subject does not
		// exist, not that we failed to find it.
		return catalog.Outcome{
			Result:  finding.NotApplicable,
			Subject: subject,
			Detail: fmt.Sprintf(
				"This kernel does not expose %s (%s); the feature is not built in, its module is not loaded, or the LSM providing it is disabled.",
				r.Key, r.Path),
		}, true

	case fact.SysctlDenied:
		// It exists and we were refused. It may be set wrong; we cannot see.
		return catalog.Outcome{
			Result:        finding.Unknown,
			UnknownReason: finding.ReasonPermission,
			Subject:       subject,
			Detail: fmt.Sprintf(
				"%s could not be read (%s): %s. The parameter exists, so its value may or may not be correct; run as root to determine it.",
				r.Key, r.Path, r.Msg),
			Evidence: []finding.Evidence{finding.NewEvidence(r.Path, 0, r.Msg, "")},
		}, true

	default:
		return catalog.Outcome{
			Result:        finding.Unknown,
			UnknownReason: finding.ReasonAmbiguousState,
			Subject:       subject,
			Detail:        fmt.Sprintf("%s could not be read (%s): %s.", r.Key, r.Path, r.Msg),
			Evidence:      []finding.Evidence{finding.NewEvidence(r.Path, 0, r.Msg, "")},
		}, true
	}
}

// unparseable is the outcome for an observed value that is not the integer the
// parameter is documented to hold.
//
// This path is reachable in practice: a parameter can change type between
// kernel versions, and a container runtime can mount something else over
// /proc/sys. Returning a fabricated zero here would be a fabricated FAIL, and
// defaulting to the safe value would be a fabricated PASS. Neither is
// available to us.
func unparseable(r fact.SysctlRunning, subject string) catalog.Outcome {
	return catalog.Outcome{
		Result:        finding.Unknown,
		UnknownReason: finding.ReasonParse,
		Subject:       subject,
		Detail: fmt.Sprintf(
			"%s holds %q, which is not the single integer this parameter is documented to contain; its meaning cannot be determined.",
			r.Key, r.Value),
		Evidence: []finding.Evidence{evidenceFor(r)},
	}
}

// evidenceFor cites a running parameter.
//
// There is no digest: /proc/sys is generated by the kernel on read and is not
// stored in the bundle's evidence store, so there is nothing an auditor could
// re-read and hash. Passing an empty digest is the honest representation of
// that, and is why ADR-0009 makes the field optional.
func evidenceFor(r fact.SysctlRunning) finding.Evidence {
	return finding.NewEvidence(r.Path, 0, fmt.Sprintf("%s = %s", r.Key, r.Value), "")
}

// evidenceForSetting cites a configuration line, with the digest of the file it
// came from so an auditor can verify it against the bundle.
func evidenceForSetting(sc fact.Sysctl, set fact.SysctlSetting) finding.Evidence {
	return finding.NewEvidence(
		set.File, set.Line,
		fmt.Sprintf("%s = %s", set.Key, set.Value),
		sc.Digests[set.File])
}

// intCheck builds the Eval for the common shape: read one integer parameter,
// pass when it satisfies a predicate, fail otherwise.
//
// pass reports whether the observed integer is acceptable. detail renders the
// human explanation for both outcomes, which keeps the PASS and FAIL wording
// of one check in one place — a correct verdict with a misleading explanation
// is its own bug.
func intCheck(
	key string,
	pass func(int) bool,
	failSeverity func(int) finding.Severity,
	detail func(n int, ok bool) string,
) func(*fact.Set) catalog.Outcome {
	return func(fs *fact.Set) catalog.Outcome {
		sc := sysctlFact(fs)

		r, probed := sc.Run(key)
		if !probed {
			// The collector never asked for this key. That is a wiring bug in
			// this repository, not an observation about the host, and it must
			// not look like one.
			return catalog.Outcome{
				Result:        finding.Unknown,
				UnknownReason: finding.ReasonInternal,
				Subject:       key,
				Detail:        fmt.Sprintf("%s was not collected; the KERNEL collector does not probe it.", key),
			}
		}
		if out, done := unreadable(r, key); done {
			return out
		}

		n, ok := r.Int()
		if !ok {
			return unparseable(r, key)
		}

		ev := []finding.Evidence{evidenceFor(r)}
		if pass(n) {
			return catalog.Outcome{
				Result:   finding.Pass,
				Subject:  key,
				Detail:   detail(n, true),
				Evidence: ev,
			}
		}
		out := catalog.Outcome{
			Result:   finding.Fail,
			Subject:  key,
			Detail:   detail(n, false),
			Evidence: ev,
		}
		if failSeverity != nil {
			out.Severity = failSeverity(n)
		}
		// Where the configuration disagrees with the running kernel, say so on
		// the failing finding too. An operator whose file already holds the
		// right value needs to know a reboot is the fix, not another edit.
		note, ev := driftNote(sc, key, r.Value)
		out.Detail += note
		out.Evidence = append(out.Evidence, ev...)
		return out
	}
}

// driftNote returns the sentence and evidence to append to a failing finding
// when the configuration sets this parameter to something other than what is
// running.
//
// It is the reason KERNEL-0007 is not the module's only use of the configured
// values. A finding that says only "ASLR is off" sends an operator to edit a
// file that already says 2; a finding that says "and your configuration
// already sets 2" sends them to reboot instead. Same verdict, different
// afternoon.
//
// Nothing is returned when the parameter is set in more than one file with
// different values: which one wins is undetermined (see
// fact.Sysctl.ConfiguredConflict), and KERNEL-0007 reports that ambiguity on
// its own rather than every check repeating a guess about it.
func driftNote(sc fact.Sysctl, key, running string) (string, []finding.Evidence) {
	set, found := sc.EffectiveConfigured(key)
	if !found || sc.ConfiguredConflict(key) {
		return "", nil
	}
	if strings.TrimSpace(set.Value) == strings.TrimSpace(running) {
		return "", nil
	}
	return fmt.Sprintf(
			" %s is configured as %q at %s:%d, so the running kernel does not match its own configuration; see KERNEL-0007.",
			key, set.Value, set.File, set.Line),
		[]finding.Evidence{evidenceForSetting(sc, set)}
}

// runningFor resolves one parameter to the outcome that describes it when it
// has no usable value, or to the value itself when it does. It is the front
// half of every check that is not built from intCheck.
func runningFor(sc fact.Sysctl, key string) (fact.SysctlRunning, catalog.Outcome, bool) {
	r, probed := sc.Run(key)
	if !probed {
		// The collector never asked for this key. That is a wiring bug in this
		// repository, not an observation about the host.
		return r, catalog.Outcome{
			Result:        finding.Unknown,
			UnknownReason: finding.ReasonInternal,
			Subject:       key,
			Detail:        fmt.Sprintf("%s was not collected; the KERNEL collector does not probe it.", key),
		}, false
	}
	if out, done := unreadable(r, key); done {
		return r, out, false
	}
	return r, catalog.Outcome{}, true
}

// joinKeys renders a sorted key list for a detail string.
func joinKeys(in []string) string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return strings.Join(out, ", ")
}
