package walker

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/antaryx/plumbline/internal/fact"
	"github.com/antaryx/plumbline/internal/system"
	"github.com/antaryx/plumbline/internal/system/fake"
)

// ownerUID is the tally the FILESYS module registers, restated here so these
// tests exercise the mechanism without importing the module that uses it.
func ownerUID() Tally {
	return Tally{Name: "owner_uid", Key: func(fi system.FileInfo) (uint64, bool) { return uint64(fi.UID), true }}
}

// tallyTree writes a fixture whose ownership the test controls, because git
// cannot carry uids and the fake's manifest is the only place they can be
// stated.
//
// owners maps a path under the root to "uid:gid".
func tallyTree(t *testing.T, owners map[string]string, files ...string) system.System {
	t.Helper()

	root := t.TempDir()
	for _, f := range files {
		p := filepath.Join(root, f)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.MkdirAll(filepath.Join(root, "_plumbline"), 0o755); err != nil {
		t.Fatal(err)
	}
	manifest := `{"description":"generated by tally_test","owners":{`
	first := true
	for p, o := range owners {
		if !first {
			manifest += ","
		}
		first = false
		manifest += fmt.Sprintf("%q:%q", p, o)
	}
	manifest += "}}"
	if err := os.WriteFile(filepath.Join(root, "_plumbline", "fixture.json"), []byte(manifest), 0o644); err != nil {
		t.Fatal(err)
	}

	s, err := fake.New(root)
	if err != nil {
		t.Fatalf("load generated fixture: %v", err)
	}
	return s
}

func tallyFact(t *testing.T, res Result, name string) fact.FSTally {
	t.Helper()
	for _, f := range res.TallyFacts {
		if f.Tally == name {
			return f
		}
	}
	t.Fatalf("no tally fact %q in %v", name, res.TallyFacts)
	return fact.FSTally{}
}

// TestATallyCountsEveryInodeWithoutRecordingOne is the property the whole
// mechanism exists for.
//
// An Interest would need one row per matching inode, so a question about
// ownership would need a row for every file on the host. A Tally holds one
// bucket per distinct owner and counts without bound inside it — so the fact
// describes six inodes while storing two entries, and would describe six
// million the same way.
func TestATallyCountsEveryInodeWithoutRecordingOne(t *testing.T) {
	s := tallyTree(t,
		map[string]string{
			"/srv/a.txt": "1000:1000",
			"/srv/b.txt": "1000:1000",
			"/srv/c.txt": "1000:1000",
			"/srv/d.txt": "4242:4242",
		},
		"srv/a.txt", "srv/b.txt", "srv/c.txt", "srv/d.txt")

	res, err := Walk(context.Background(), s, Config{Tallies: []Tally{ownerUID()}})
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	got := tallyFact(t, res, "owner_uid")

	// Three distinct owners: root (the tree's own directories), 1000 and 4242.
	if len(got.Buckets) != 3 {
		t.Fatalf("buckets = %d, want 3 (root, 1000, 4242): %+v", len(got.Buckets), got.Buckets)
	}
	if b, ok := got.Bucket(1000); !ok || b.Count != 3 {
		t.Errorf("uid 1000 bucket = %+v, ok=%v; want count 3", b, ok)
	}
	if b, ok := got.Bucket(4242); !ok || b.Count != 1 {
		t.Errorf("uid 4242 bucket = %+v, ok=%v; want count 1", b, ok)
	}
	if _, ok := got.Bucket(9999); ok {
		t.Error("an owner nothing has reports a bucket")
	}
	if got.Total() != got.InodesTallied {
		t.Errorf("Total()=%d but InodesTallied=%d; nothing was dropped, so they must agree", got.Total(), got.InodesTallied)
	}
	if !got.Complete() {
		t.Errorf("a walk that finished reports an incomplete tally: %v", got.TruncationReasons)
	}
}

// TestTheExemplarIsTheFirstInodeInWalkOrder. A count alone tells an operator
// there is a problem and not where to look, so each bucket keeps one path —
// and it has to be the same path on every run, or two collections of an
// unchanged host produce different facts.
func TestTheExemplarIsTheFirstInodeInWalkOrder(t *testing.T) {
	owners := map[string]string{
		"/srv/aaa.txt": "4242:0",
		"/srv/mmm.txt": "4242:0",
		"/srv/zzz.txt": "4242:0",
	}
	files := []string{"srv/zzz.txt", "srv/mmm.txt", "srv/aaa.txt"}

	var seen string
	for i := 0; i < 5; i++ {
		s := tallyTree(t, owners, files...)
		res, err := Walk(context.Background(), s, Config{Tallies: []Tally{ownerUID()}})
		if err != nil {
			t.Fatalf("Walk: %v", err)
		}
		b, ok := tallyFact(t, res, "owner_uid").Bucket(4242)
		if !ok {
			t.Fatal("uid 4242 has no bucket")
		}
		if b.Example.Path != "/srv/aaa.txt" {
			t.Fatalf("exemplar = %q, want /srv/aaa.txt: directory entries are walked in sorted order", b.Example.Path)
		}
		if seen != "" && b.Example.Path != seen {
			t.Fatalf("exemplar moved between runs: %q then %q", seen, b.Example.Path)
		}
		seen = b.Example.Path
	}
}

// TestTheKeyspaceCapTruncatesOnlyItsOwnTally, and truncates for a reason that
// says what actually happened. A key cap is not a row cap: the walk kept
// counting every inode it met and only stopped admitting new buckets, so an
// operator raising MaxHits would fix nothing.
func TestTheKeyspaceCapTruncatesOnlyItsOwnTally(t *testing.T) {
	owners := map[string]string{}
	var files []string
	for i := 0; i < 8; i++ {
		p := fmt.Sprintf("srv/f%d.txt", i)
		files = append(files, p)
		owners["/"+p] = fmt.Sprintf("%d:0", 5000+i)
	}

	narrow := ownerUID()
	narrow.MaxKeys = 3
	wide := Tally{Name: "owner_gid", Key: func(fi system.FileInfo) (uint64, bool) { return uint64(fi.GID), true }}

	res, err := Walk(context.Background(), tallyTree(t, owners, files...), Config{Tallies: []Tally{narrow, wide}})
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}

	capped := tallyFact(t, res, "owner_uid")
	if len(capped.Buckets) != 3 {
		t.Errorf("buckets = %d, want the cap of 3", len(capped.Buckets))
	}
	if capped.KeysDropped == 0 {
		t.Error("the cap fired but no dropped keys were counted")
	}
	if capped.Complete() {
		t.Error("a tally that discarded keys reports Complete; every absence claim over it would be false assurance")
	}
	if !hasTallyReason(capped, fact.TruncMaxKeys) {
		t.Errorf("reasons = %v, want %s", capped.TruncationReasons, fact.TruncMaxKeys)
	}
	// The counting never stopped, only the admitting of new keys did.
	if capped.InodesTallied <= capped.Total() {
		t.Errorf("InodesTallied=%d, bucket total=%d: a key cap must keep counting inodes it could not bucket",
			capped.InodesTallied, capped.Total())
	}

	// The other tally saw the same walk and is untouched by its neighbour's
	// cap, which is the reason there is one fact per question.
	other := tallyFact(t, res, "owner_gid")
	if !other.Complete() {
		t.Errorf("owner_gid was truncated by owner_uid's cap: %v", other.TruncationReasons)
	}
}

// TestAGlobalLimitTruncatesTalliesToo. MaxKeys is per-tally; the inode budget,
// the deadline and an unreadable directory are properties of the traversal and
// have to land on every fact it produced, aggregates included.
func TestAGlobalLimitTruncatesTalliesToo(t *testing.T) {
	owners := map[string]string{}
	var files []string
	for i := 0; i < 20; i++ {
		p := fmt.Sprintf("srv/f%d.txt", i)
		files = append(files, p)
		owners["/"+p] = "1000:1000"
	}

	res, err := Walk(context.Background(), tallyTree(t, owners, files...), Config{
		Tallies:   []Tally{ownerUID()},
		Interests: []Interest{{Name: "everything", Match: func(system.FileInfo) bool { return true }}},
		MaxInodes: 4,
	})
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}

	got := tallyFact(t, res, "owner_uid")
	if got.Complete() {
		t.Fatal("the inode budget fired and the tally still reports Complete")
	}
	if !hasTallyReason(got, fact.TruncInodes) {
		t.Errorf("reasons = %v, want %s", got.TruncationReasons, fact.TruncInodes)
	}
	// And the rows fact records the same limit, because it is one walk.
	if res.Facts[0].Complete() {
		t.Error("the interest fact escaped a global limit the tally recorded")
	}
}

// TestATallyThatDeclinesAnInodeDoesNotBucketIt. Returning false from Key means
// "outside this question", which must not be recorded as key zero — a bucket
// that is an artefact of the tally rather than an observation about the host.
func TestATallyThatDeclinesAnInodeDoesNotBucketIt(t *testing.T) {
	s := tallyTree(t,
		map[string]string{"/srv/a.txt": "1000:0", "/srv/b.txt": "1000:0"},
		"srv/a.txt", "srv/b.txt")

	only1000 := Tally{
		Name: "owner_uid",
		Key: func(fi system.FileInfo) (uint64, bool) {
			if fi.UID != 1000 {
				return 0, false
			}
			return uint64(fi.UID), true
		},
	}
	res, err := Walk(context.Background(), s, Config{Tallies: []Tally{only1000}})
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	got := tallyFact(t, res, "owner_uid")

	if _, ok := got.Bucket(0); ok {
		t.Error("a declined inode was bucketed into key 0")
	}
	if len(got.Buckets) != 1 {
		t.Fatalf("buckets = %+v, want only uid 1000", got.Buckets)
	}
	if got.InodesTallied != 2 {
		t.Errorf("InodesTallied = %d, want 2", got.InodesTallied)
	}
	if got.InodesVisited <= got.InodesTallied {
		t.Errorf("InodesVisited=%d must exceed InodesTallied=%d: the walk saw directories this tally declined",
			got.InodesVisited, got.InodesTallied)
	}
}

func TestRegisterTallyRejectsBadTallies(t *testing.T) {
	cases := map[string]Tally{
		"empty name":  {Key: func(system.FileInfo) (uint64, bool) { return 0, true }},
		"separator":   {Name: "owner.uid", Key: func(system.FileInfo) (uint64, bool) { return 0, true }},
		"no key func": {Name: "owner_uid"},
	}
	for name, tal := range cases {
		t.Run(name, func(t *testing.T) {
			t.Cleanup(resetRegistry)
			resetRegistry()
			defer func() {
				if recover() == nil {
					t.Errorf("RegisterTally(%+v) did not panic", tal)
				}
			}()
			RegisterTally(tal)
		})
	}
}

func TestRegisterTallyRejectsDuplicatesAndLateArrivals(t *testing.T) {
	t.Run("duplicate", func(t *testing.T) {
		t.Cleanup(resetRegistry)
		resetRegistry()
		RegisterTally(ownerUID())
		defer func() {
			if recover() == nil {
				t.Error("a duplicate tally name did not panic")
			}
		}()
		RegisterTally(ownerUID())
	})

	t.Run("after sealing", func(t *testing.T) {
		t.Cleanup(resetRegistry)
		resetRegistry()
		_ = Interests() // seals both registries
		defer func() {
			if recover() == nil {
				t.Error("registering a tally after the set was read did not panic")
			}
		}()
		RegisterTally(ownerUID())
	})
}

// TestCollectorPublishesTallyFacts pins the fact namespace and the wiring. The
// IDs appear in bundles on disk and in users' suppression files.
func TestCollectorPublishesTallyFacts(t *testing.T) {
	t.Cleanup(resetRegistry)
	resetRegistry()
	Register(Interest{Name: "suid", Match: suid})
	RegisterTally(ownerUID())

	want := []fact.ID{"fs.suid", "fs.tally.owner_uid", fact.MountsID}
	got := New().Produces()
	if len(got) != len(want) {
		t.Fatalf("Produces = %v, want %v", got, want)
	}
	for n := range want {
		if got[n] != want[n] {
			t.Fatalf("Produces = %v, want %v", got, want)
		}
	}

	set := fact.NewSet()
	if err := New().Collect(context.Background(), fixture(t, "fswalk-basic"), set); err != nil {
		t.Fatalf("Collect: %v", err)
	}
	f, ferr, ok := fact.Get[fact.FSTally](set, "fs.tally.owner_uid")
	if !ok {
		t.Fatalf("fs.tally.owner_uid missing after Collect (err=%v)", ferr)
	}
	if f.FactID() != "fs.tally.owner_uid" {
		t.Errorf("fact reports ID %s", f.FactID())
	}
	if f.InodesVisited == 0 {
		t.Error("the tally records no inodes visited; the shared counter was not stamped")
	}
}

// TestATallyAloneIsEnoughToJustifyAWalk. A module may want only an aggregate,
// and refusing to walk for it would silently produce no fact at all.
func TestATallyAloneIsEnoughToJustifyAWalk(t *testing.T) {
	t.Cleanup(resetRegistry)
	resetRegistry()
	RegisterTally(ownerUID())

	s := fixture(t, "fswalk-basic")
	set := fact.NewSet()
	if err := New().Collect(context.Background(), s, set); err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if s.totalReadDirs() == 0 {
		t.Error("a registered tally did not cause the tree to be walked")
	}
	if _, _, ok := fact.Get[fact.FSTally](set, "fs.tally.owner_uid"); !ok {
		t.Error("the tally fact was not published")
	}
}

func TestWalkRejectsNoQuestions(t *testing.T) {
	if _, err := Walk(context.Background(), fixture(t, "fswalk-basic"), Config{}); err == nil {
		t.Error("Walk with neither interests nor tallies should be a caller error")
	}
}

func TestTallyFactIDNaming(t *testing.T) {
	if got, want := fact.FSTallyFactID("owner_uid"), fact.ID("fs.tally.owner_uid"); got != want {
		t.Errorf("FSTallyFactID(owner_uid) = %q, want %q", got, want)
	}
}

// hasTallyReason is hasReason for the aggregating fact. The two fact types
// carry the same reason list and no common method set, so the helper is
// duplicated rather than abstracted — see mustBeCompleteTally in the FILESYS
// checks for the same call, made for the same reason.
func hasTallyReason(t fact.FSTally, want fact.TruncationReason) bool {
	for _, r := range t.TruncationReasons {
		if r == want {
			return true
		}
	}
	return false
}
